Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.network "private_network", ip: "192.168.57.10"
  config.vm.network "public_network"

  config.vm.provision "shell", path: "provision.sh"
end